services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/project
    networks:
      - micro_network
    volumes:
      - .:/var/www/project
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      APP_ENV: ${APP_ENV:-dev}
      PHP_IDE_CONFIG: "serverName=localhost"

  web:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - micro_network
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - app



networks:
  micro_network:
    driver: bridge